version: '3.9'

services:
    go_env:
        container_name: golang_env
        image: go_env:latest
        command: 'sleep infinity'
        build: .
        volumes:
            - ./:/home/ec2-user/workspace/
